### ISSUE TITLE
Problem running server...

### ISSUE THREAD

**Issue by phaus** [FND/statusq#1]
I did 

easy_install pip
pip instal Flask ( following guide at http://flask.pocoo.org/ )

i got an error:

imotep:statusq philipp$ ./server
Traceback (most recent call last):
  File "./server", line 34, in <module>
    status = not main(sys.argv)
  File "./server", line 26, in main
    from statusq import app
  File "/Users/philipp/GIT/statusq/statusq/**init**.py", line 5, in <module>
    from flask import Flask
ImportError: No module named flask

I have MacOS (_sic_) 10.7. python is:
imotep:statusq philipp$ python --version
Python 2.7.2

**Comment by FND** [comment]
Well, that seems odd - not sure what's going on there (though I vaguely remember some @tiddlyweb colleagues having site-packages issues on their OS X machines, in a galaxy far, far away.).

Try using a virtual environment instead:

```
$ pip install virtualenv
$ make init # see Makefile for details
```

**Comment by phaus** [comment]
Imotep:statusq philipp$ make init
virtualenv --no-site-packages venv
`The --no-site-packages flag is deprecated; it is now the default behavior.
New python executable in venv/bin/python
Installing setuptools.............done.
Installing pip...............done.
ln -s venv/bin/activate
ln: ./activate: File exists
make: *** [env] Error 1`

**Comment by phaus** [comment]
i made it finally work.

```
source activate 
```

was the missing thing :-)
